/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#include "s21_matrix.h"

/*
Tests with too large values:

Incorrect_input_parameters_8
Incorrect_input_parameters_s21_sum_matrix_3
Incorrect_input_parameters_s21_sum_matrix_4
Incorrect_input_parameters_s21_sub_matrix_3
Incorrect_input_parameters_s21_sub_matrix_4
*/

// s21_create_matrix

START_TEST(Incorrect_input_parameters_1) {
  matrix_t result;
  int error_code = s21_create_matrix(-1, 2, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_2) {
  matrix_t result;
  int error_code = s21_create_matrix(1, -2, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_3) {
  int error_code = s21_create_matrix(1, 2, NULL);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_4) {
  matrix_t result;
  int error_code = s21_create_matrix(3, 0, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_5) {
  matrix_t result;
  int error_code = s21_create_matrix(0, 3, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_6) {
  matrix_t result;
  int error_code = s21_create_matrix(0, 0, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_7) {
  int error_code = s21_create_matrix(0, 0, NULL);
  ck_assert_int_eq(error_code, 1);

  // #test Incorrect_input_parameters_8
  // matrix_t result;
  // int error_code = s21_create_matrix(2147483647, 2147483647, &result);
  // ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_9) {
  matrix_t result;
  int error_code = s21_create_matrix(1147483647, 0, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Correct_input_parameters_10) {
  matrix_t result;
  int error_code = s21_create_matrix(1, 1, &result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_11) {
  matrix_t result;
  int error_code = s21_create_matrix(2, 6, &result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_12) {
  matrix_t result;
  int error_code = s21_create_matrix(6, 2, &result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_13) {
  matrix_t result;
  int error_code = s21_create_matrix(100, 100, &result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_14) {
  matrix_t result;
  int error_code = s21_create_matrix(1000, 1000, &result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_15) {
  matrix_t result;
  result.rows = 10;
  result.columns = 10;
  int error_code = s21_create_matrix(1000, 1000, &result);
  ck_assert_int_eq(error_code, 0);

  // s21_remove_matrix
}
END_TEST

START_TEST(Correct_input_parameters_remove_matrix_1) {
  matrix_t result;
  s21_create_matrix(3, 3, &result);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(Incorrect_input_parameters_remove_matrix_1) {
  matrix_t result;
  result.matrix = NULL;
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(Incorrect_input_parameters_remove_matrix_2) {
  matrix_t result;
  s21_create_matrix(3, 3, &result);
  s21_remove_matrix(NULL);

  // s21_eq_matrix
}
END_TEST

START_TEST(Correct_input_parameters_s21_eq_matrix_1) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(10, 10, &my_matrix);
  s21_create_matrix(10, 10, &my_matrix2);
  int error_code = s21_eq_matrix(&my_matrix, &my_matrix2);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Correct_input_parameters_s21_eq_matrix_2) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  int error_code = s21_eq_matrix(&my_matrix, &my_matrix2);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Correct_input_parameters_s21_eq_matrix_3) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  int error_code = s21_eq_matrix(&my_matrix, &my_matrix2);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_eq_matrix_1) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(1001, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  int error_code = s21_eq_matrix(&my_matrix, &my_matrix2);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_eq_matrix_2) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(1000, 1001, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  int error_code = s21_eq_matrix(&my_matrix, &my_matrix2);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_eq_matrix_3) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(1001, 1001, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  int error_code = s21_eq_matrix(&my_matrix, &my_matrix2);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_eq_matrix_4) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(1001, 1000, &my_matrix);
  s21_create_matrix(1000, 1001, &my_matrix2);
  int error_code = s21_eq_matrix(&my_matrix, &my_matrix2);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_eq_matrix_5) {
  matrix_t my_matrix;
  s21_create_matrix(1001, 1000, &my_matrix);
  int error_code = s21_eq_matrix(&my_matrix, NULL);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_eq_matrix_6) {
  matrix_t my_matrix2;
  s21_create_matrix(1000, 1001, &my_matrix2);
  int error_code = s21_eq_matrix(NULL, &my_matrix2);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_eq_matrix_7) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  my_matrix.matrix[0][0] = 2;
  my_matrix2.matrix[0][0] = 1;
  int error_code = s21_eq_matrix(&my_matrix, &my_matrix2);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_eq_matrix_8) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  my_matrix.matrix[131][131] = 211;
  my_matrix2.matrix[131][132] = 210.9;
  int error_code = s21_eq_matrix(&my_matrix, &my_matrix2);
  ck_assert_int_eq(error_code, 0);

  // s21_sum_matrix
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sum_matrix_1) {
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(20, 10, &my_matrix2);
  int error_code = s21_sum_matrix(NULL, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sum_matrix_2) {
  matrix_t my_matrix;
  matrix_t my_result;
  s21_create_matrix(10, 20, &my_matrix);
  int error_code = s21_sum_matrix(&my_matrix, NULL, &my_result);
  ck_assert_int_eq(error_code, 1);

  // #test Incorrect_input_parameters_s21_sum_matrix_3
  // matrix_t my_matrix;
  // matrix_t my_matrix2;
  // matrix_t my_result;
  // s21_create_matrix(2147483647, 10, &my_matrix);
  // s21_create_matrix(10, 10, &my_matrix2);
  // int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  // ck_assert_int_eq(error_code, 1);

  // #test Incorrect_input_parameters_s21_sum_matrix_4
  // matrix_t my_matrix;
  // matrix_t my_matrix2;
  // matrix_t my_result;
  // s21_create_matrix(10, 10, &my_matrix);
  // s21_create_matrix(2147483647, 10, &my_matrix2);
  // int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  // ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sum_matrix_5) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(10, 20, &my_matrix);
  s21_create_matrix(20, 10, &my_matrix2);
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sum_matrix_6) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(20, 10, &my_matrix);
  s21_create_matrix(10, 20, &my_matrix2);
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sum_matrix_7) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(20, 20, &my_matrix);
  s21_create_matrix(10, 20, &my_matrix2);
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sum_matrix_8) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(20, 10, &my_matrix);
  s21_create_matrix(20, 20, &my_matrix2);
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sum_matrix_9) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  s21_create_matrix(100, 100, &my_matrix2);
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sum_matrix_10) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sum_matrix_11) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  my_matrix.matrix[31][31] = 149;
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sum_matrix_12) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 100.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sum_matrix_13) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sum_matrix_14) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 91.0 + j + 1.0;
    }
  }
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sum_matrix_15) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sum_matrix_16) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_sum_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);

  // s21_sub_matrix
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sub_matrix_1) {
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(20, 10, &my_matrix2);
  int error_code = s21_sub_matrix(NULL, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sub_matrix_2) {
  matrix_t my_matrix;
  matrix_t my_result;
  s21_create_matrix(10, 20, &my_matrix);
  int error_code = s21_sub_matrix(&my_matrix, NULL, &my_result);
  ck_assert_int_eq(error_code, 1);

  // #test Incorrect_input_parameters_s21_sub_matrix_3
  // matrix_t my_matrix;
  // matrix_t my_matrix2;
  // matrix_t my_result;
  // s21_create_matrix(2147483647, 10, &my_matrix);
  // s21_create_matrix(10, 10, &my_matrix2);
  // int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  // ck_assert_int_eq(error_code, 1);

  // #test Incorrect_input_parameters_s21_sub_matrix_4
  // matrix_t my_matrix;
  // matrix_t my_matrix2;
  // matrix_t my_result;
  // s21_create_matrix(10, 10, &my_matrix);
  // s21_create_matrix(2147483647, 10, &my_matrix2);
  // int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  // ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sub_matrix_5) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(10, 20, &my_matrix);
  s21_create_matrix(20, 10, &my_matrix2);
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sub_matrix_6) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(20, 10, &my_matrix);
  s21_create_matrix(10, 20, &my_matrix2);
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sub_matrix_7) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(20, 20, &my_matrix);
  s21_create_matrix(10, 20, &my_matrix2);
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_sub_matrix_8) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(20, 10, &my_matrix);
  s21_create_matrix(20, 20, &my_matrix2);
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sub_matrix_9) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  s21_create_matrix(100, 100, &my_matrix2);
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sub_matrix_10) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sub_matrix_11) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  my_matrix.matrix[31][31] = 149;
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sub_matrix_12) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 100.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sub_matrix_13) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sub_matrix_14) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 91.0 + j + 1.0;
    }
  }
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sub_matrix_15) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_sub_matrix_16) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1000, 1000, &my_matrix);
  s21_create_matrix(1000, 1000, &my_matrix2);
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_sub_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);

  // s21_mult_number
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_number_1) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  int error_code = s21_mult_number(&my_matrix, 3.0, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_number_2) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  int error_code = s21_mult_number(&my_matrix, -3.0, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_number_3) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  int error_code = s21_mult_number(&my_matrix, 300.1234, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_number_4) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  int error_code = s21_mult_number(&my_matrix, -300.1234, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_number_5) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  int error_code = s21_mult_number(&my_matrix, 0.0, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_number_6) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  int error_code = s21_mult_number(&my_matrix, 1.0, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_number_7) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  int error_code = s21_mult_number(&my_matrix, 1e308, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_number_8) {
  matrix_t my_result;
  int error_code = s21_mult_number(NULL, 3.0, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_number_9) {
  matrix_t my_matrix;
  s21_create_matrix(100, 100, &my_matrix);
  int error_code = s21_mult_number(&my_matrix, 3.0, NULL);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_number_10) {
  matrix_t my_matrix = {0};
  my_matrix.rows = 2;
  my_matrix.columns = 2;
  my_matrix.matrix = NULL;
  matrix_t my_result;
  int error_code = s21_mult_number(&my_matrix, 30.0, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_number_11) {
  matrix_t my_matrix = {0};
  my_matrix.rows = -2;
  my_matrix.columns = 2;
  my_matrix.matrix = NULL;
  matrix_t my_result;
  int error_code = s21_mult_number(&my_matrix, 30.0, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_number_12) {
  matrix_t my_matrix = {0};
  my_matrix.rows = 2;
  my_matrix.columns = -2;
  my_matrix.matrix = NULL;
  matrix_t my_result;
  int error_code = s21_mult_number(&my_matrix, 30.0, &my_result);
  ck_assert_int_eq(error_code, 1);

  // s21_mult_matrix
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_matrix_1) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(100, 100, &my_matrix);
  s21_create_matrix(100, 100, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_matrix_2) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(12, 99, &my_matrix);
  s21_create_matrix(99, 12, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_matrix_3) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(1, 1, &my_matrix);
  s21_create_matrix(1, 1, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_mult_matrix_4) {
  matrix_t my_matrix = {0};
  matrix_t my_matrix2 = {0};
  matrix_t my_result = {0};
  s21_create_matrix(10, 123, &my_matrix);
  s21_create_matrix(123, 55, &my_matrix2);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  for (int i = 0; i < my_matrix2.rows; i++) {
    for (int j = 0; j < my_matrix2.columns; j++) {
      my_matrix2.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_1) {
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(123, 55, &my_matrix2);
  int error_code = s21_mult_matrix(NULL, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_2) {
  matrix_t my_matrix;
  matrix_t my_result;
  s21_create_matrix(10, 123, &my_matrix);
  int error_code = s21_mult_matrix(&my_matrix, NULL, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_3) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  s21_create_matrix(10, 123, &my_matrix);
  s21_create_matrix(123, 55, &my_matrix2);
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, NULL);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_4) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(10, 122, &my_matrix);
  s21_create_matrix(123, 55, &my_matrix2);
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_5) {
  matrix_t my_matrix = {0};
  my_matrix.rows = 2;
  my_matrix.columns = 3;
  my_matrix.matrix = NULL;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(123, 55, &my_matrix2);
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_6) {
  matrix_t my_matrix;
  matrix_t my_matrix2 = {0};
  my_matrix2.rows = 2;
  my_matrix2.columns = 3;
  my_matrix2.matrix = NULL;
  matrix_t my_result;
  s21_create_matrix(123, 55, &my_matrix);
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_7) {
  matrix_t my_matrix;
  my_matrix.rows = -2;
  my_matrix.columns = 2;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(123, 55, &my_matrix2);
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_8) {
  matrix_t my_matrix;
  my_matrix.rows = 2;
  my_matrix.columns = -2;
  matrix_t my_matrix2;
  matrix_t my_result;
  s21_create_matrix(123, 55, &my_matrix2);
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_9) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  my_matrix2.rows = -2;
  my_matrix2.columns = 2;
  matrix_t my_result;
  s21_create_matrix(123, 55, &my_matrix);
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_10) {
  matrix_t my_matrix;
  matrix_t my_matrix2;
  my_matrix2.rows = 2;
  my_matrix2.columns = -2;
  matrix_t my_result;
  s21_create_matrix(123, 55, &my_matrix);
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_mult_matrix_11) {
  matrix_t my_matrix;
  my_matrix.rows = -2;
  my_matrix.columns = -2;
  my_matrix.matrix = NULL;
  matrix_t my_matrix2;
  my_matrix2.rows = -2;
  my_matrix2.columns = -2;
  my_matrix2.matrix = NULL;
  matrix_t my_result;
  int error_code = s21_mult_matrix(&my_matrix, &my_matrix2, &my_result);
  ck_assert_int_eq(error_code, 1);

  // s21_transpose
}
END_TEST

START_TEST(Correct_input_parameters_s21_transpose_1) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(10, 10, &my_matrix);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_transpose(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_transpose_2) {
  matrix_t my_result;
  int error_code = s21_transpose(NULL, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_transpose_3) {
  matrix_t my_matrix;
  s21_create_matrix(10, 10, &my_matrix);
  for (int i = 0; i < my_matrix.rows; i++) {
    for (int j = 0; j < my_matrix.columns; j++) {
      my_matrix.matrix[i][j] = i * 10.0 + j + 1.0;
    }
  }
  int error_code = s21_transpose(&my_matrix, NULL);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_transpose_4) {
  matrix_t my_matrix = {0};
  my_matrix.rows = -2;
  my_matrix.columns = 2;
  matrix_t my_result = {0};
  int error_code = s21_transpose(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_transpose_5) {
  matrix_t my_matrix = {0};
  my_matrix.rows = 2;
  my_matrix.columns = -2;
  matrix_t my_result = {0};
  int error_code = s21_transpose(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_transpose_6) {
  matrix_t my_matrix;
  my_matrix.rows = 2;
  my_matrix.columns = 2;
  my_matrix.matrix = NULL;
  matrix_t my_result;
  int error_code = s21_transpose(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 1);

  // s21_determinant
}
END_TEST

START_TEST(Correct_input_parameters_s21_determinant_1) {
  matrix_t my_matrix;
  double result;
  s21_create_matrix(2, 2, &my_matrix);
  my_matrix.matrix[0][0] = 5;
  my_matrix.matrix[0][1] = 2;
  my_matrix.matrix[1][0] = 3;
  my_matrix.matrix[1][1] = 6;
  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 0);
  ck_assert_double_eq(result, 24.000000);
}
END_TEST

START_TEST(Correct_input_parameters_s21_determinant_2) {
  matrix_t my_matrix;
  double result;
  s21_create_matrix(3, 3, &my_matrix);
  my_matrix.matrix[0][0] = 12;
  my_matrix.matrix[0][1] = 4;
  my_matrix.matrix[0][2] = 13;
  my_matrix.matrix[1][0] = 45;
  my_matrix.matrix[1][1] = 2;
  my_matrix.matrix[1][2] = 4;
  my_matrix.matrix[2][0] = 12;
  my_matrix.matrix[2][1] = 3;
  my_matrix.matrix[2][2] = 4;
  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 0);
  ck_assert_double_eq(result, 867.000000);
}
END_TEST

START_TEST(Correct_input_parameters_s21_determinant_3) {
  matrix_t my_matrix;
  double result;
  s21_create_matrix(4, 4, &my_matrix);
  my_matrix.matrix[0][0] = 12;
  my_matrix.matrix[0][1] = 4;
  my_matrix.matrix[0][2] = 13;
  my_matrix.matrix[0][3] = 5;
  my_matrix.matrix[1][0] = 45;
  my_matrix.matrix[1][1] = 2;
  my_matrix.matrix[1][2] = 4;
  my_matrix.matrix[1][3] = 7;
  my_matrix.matrix[2][0] = 12;
  my_matrix.matrix[2][1] = 3;
  my_matrix.matrix[2][2] = 4;
  my_matrix.matrix[2][3] = 11;
  my_matrix.matrix[3][0] = 34;
  my_matrix.matrix[3][1] = 12;
  my_matrix.matrix[3][2] = 22;
  my_matrix.matrix[3][3] = 1;

  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 0);
  ck_assert_double_eq(result, -30385.000000);
}
END_TEST

START_TEST(Correct_input_parameters_s21_determinant_4) {
  matrix_t my_matrix;
  double result;
  s21_create_matrix(4, 4, &my_matrix);
  my_matrix.matrix[0][0] = 0.0;
  my_matrix.matrix[0][1] = 0.0;
  my_matrix.matrix[0][2] = 0.0;
  my_matrix.matrix[0][3] = 0.0;
  my_matrix.matrix[1][0] = 45;
  my_matrix.matrix[1][1] = 2;
  my_matrix.matrix[1][2] = 4;
  my_matrix.matrix[1][3] = 7;
  my_matrix.matrix[2][0] = 12;
  my_matrix.matrix[2][1] = 3;
  my_matrix.matrix[2][2] = 4;
  my_matrix.matrix[2][3] = 11;
  my_matrix.matrix[3][0] = 34;
  my_matrix.matrix[3][1] = 12;
  my_matrix.matrix[3][2] = 22;
  my_matrix.matrix[3][3] = 1;

  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 0);
  ck_assert_double_eq(result, 0);
}
END_TEST

START_TEST(Correct_input_parameters_s21_determinant_5) {
  matrix_t my_matrix;
  double result;
  s21_create_matrix(1, 1, &my_matrix);
  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_determinant_1) {
  double result;
  int error_code = s21_determinant(NULL, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_determinant_2) {
  matrix_t my_matrix;
  s21_create_matrix(2, 2, &my_matrix);
  my_matrix.matrix[0][0] = 5;
  my_matrix.matrix[0][1] = 2;
  my_matrix.matrix[1][0] = 3;
  my_matrix.matrix[1][1] = 6;
  int error_code = s21_determinant(&my_matrix, NULL);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_determinant_3) {
  matrix_t my_matrix;
  double result;
  my_matrix.rows = -2;
  my_matrix.columns = 2;
  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_determinant_4) {
  matrix_t my_matrix;
  double result;
  my_matrix.rows = 2;
  my_matrix.columns = -2;
  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_determinant_5) {
  matrix_t my_matrix;
  double result;
  my_matrix.rows = 2;
  my_matrix.columns = 2;
  my_matrix.matrix = NULL;
  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_determinant_6) {
  matrix_t my_matrix;
  double result;
  my_matrix.rows = -2;
  my_matrix.columns = -3;
  my_matrix.matrix = NULL;
  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_determinant_7) {
  matrix_t my_matrix;
  double result;
  s21_create_matrix(10, 11, &my_matrix);
  int error_code = s21_determinant(&my_matrix, &result);
  ck_assert_int_eq(error_code, 2);

  // s21_calc_complements
}
END_TEST

START_TEST(Correct_input_parameters_s21_calc_complements_1) {
  matrix_t my_matrix;
  matrix_t my_result;
  matrix_t my_matrix_test;
  s21_create_matrix(3, 3, &my_matrix_test);
  my_matrix_test.matrix[0][0] = 0;
  my_matrix_test.matrix[0][1] = 10;
  my_matrix_test.matrix[0][2] = -20;
  my_matrix_test.matrix[1][0] = 4;
  my_matrix_test.matrix[1][1] = -14;
  my_matrix_test.matrix[1][2] = 8;
  my_matrix_test.matrix[2][0] = -8;
  my_matrix_test.matrix[2][1] = -2;
  my_matrix_test.matrix[2][2] = 4;
  s21_create_matrix(3, 3, &my_matrix);
  my_matrix.matrix[0][0] = 1;
  my_matrix.matrix[0][1] = 2;
  my_matrix.matrix[0][2] = 3;
  my_matrix.matrix[1][0] = 0;
  my_matrix.matrix[1][1] = 4;
  my_matrix.matrix[1][2] = 2;
  my_matrix.matrix[2][0] = 5;
  my_matrix.matrix[2][1] = 2;
  my_matrix.matrix[2][2] = 1;
  int error_code = s21_calc_complements(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 0);
  ck_assert_double_eq(my_result.matrix[0][0], my_matrix_test.matrix[0][0]);
  ck_assert_double_eq(my_result.matrix[0][1], my_matrix_test.matrix[0][1]);
  ck_assert_double_eq(my_result.matrix[0][2], my_matrix_test.matrix[0][2]);
  ck_assert_double_eq(my_result.matrix[1][0], my_matrix_test.matrix[1][0]);
  ck_assert_double_eq(my_result.matrix[1][1], my_matrix_test.matrix[1][1]);
  ck_assert_double_eq(my_result.matrix[1][2], my_matrix_test.matrix[1][2]);
  ck_assert_double_eq(my_result.matrix[2][0], my_matrix_test.matrix[2][0]);
  ck_assert_double_eq(my_result.matrix[2][1], my_matrix_test.matrix[2][1]);
  ck_assert_double_eq(my_result.matrix[2][2], my_matrix_test.matrix[2][2]);
}
END_TEST

START_TEST(Correct_input_parameters_s21_calc_complements_2) {
  matrix_t my_matrix;
  matrix_t my_result;
  s21_create_matrix(1, 1, &my_matrix);
  my_matrix.matrix[0][0] = 1;
  int error_code = s21_calc_complements(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 0);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_calc_complements_1) {
  matrix_t my_result;
  int error_code = s21_calc_complements(NULL, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_calc_complements_2) {
  matrix_t my_matrix;
  s21_create_matrix(3, 3, &my_matrix);
  my_matrix.matrix[0][0] = 1;
  my_matrix.matrix[0][1] = 2;
  my_matrix.matrix[0][2] = 3;
  my_matrix.matrix[1][0] = 0;
  my_matrix.matrix[1][1] = 4;
  my_matrix.matrix[1][2] = 2;
  my_matrix.matrix[2][0] = 5;
  my_matrix.matrix[2][1] = 2;
  my_matrix.matrix[2][2] = 1;
  int error_code = s21_calc_complements(&my_matrix, NULL);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_calc_complements_3) {
  matrix_t my_matrix;
  matrix_t my_result;
  my_matrix.rows = -2;
  my_matrix.columns = 2;
  int error_code = s21_calc_complements(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_calc_complements_4) {
  matrix_t my_matrix;
  matrix_t my_result;
  my_matrix.rows = 2;
  my_matrix.columns = -2;
  int error_code = s21_calc_complements(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_calc_complements_5) {
  matrix_t my_matrix;
  matrix_t my_result;
  my_matrix.rows = 2;
  my_matrix.columns = 2;
  my_matrix.matrix = NULL;
  int error_code = s21_calc_complements(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_calc_complements_6) {
  matrix_t my_matrix;
  matrix_t my_result;
  s21_create_matrix(5, 6, &my_matrix);
  int error_code = s21_calc_complements(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 2);

  // s21_inverse_matrix
}
END_TEST

START_TEST(Correct_input_parameters_s21_inverse_matrix_1) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  matrix_t my_matrix_test = {0};
  s21_create_matrix(3, 3, &my_matrix_test);
  my_matrix_test.matrix[0][0] = 0.0;
  my_matrix_test.matrix[0][1] = 1.5;
  my_matrix_test.matrix[0][2] = -0.5;
  my_matrix_test.matrix[1][0] = 1.0;
  my_matrix_test.matrix[1][1] = -4.0;
  my_matrix_test.matrix[1][2] = 1.0;
  my_matrix_test.matrix[2][0] = -0.5;
  my_matrix_test.matrix[2][1] = 1.0;
  my_matrix_test.matrix[2][2] = 0.0;
  s21_create_matrix(3, 3, &my_matrix);
  my_matrix.matrix[0][0] = 4;
  my_matrix.matrix[0][1] = 2;
  my_matrix.matrix[0][2] = 2;
  my_matrix.matrix[1][0] = 2;
  my_matrix.matrix[1][1] = 1;
  my_matrix.matrix[1][2] = 2;
  my_matrix.matrix[2][0] = 4;
  my_matrix.matrix[2][1] = 3;
  my_matrix.matrix[2][2] = 6;
  int error_code = s21_inverse_matrix(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 0);
  ck_assert_double_eq(my_result.matrix[0][0], my_matrix_test.matrix[0][0]);
  ck_assert_double_eq(my_result.matrix[0][1], my_matrix_test.matrix[0][1]);
  ck_assert_double_eq(my_result.matrix[0][2], my_matrix_test.matrix[0][2]);
  ck_assert_double_eq(my_result.matrix[1][0], my_matrix_test.matrix[1][0]);
  ck_assert_double_eq(my_result.matrix[1][1], my_matrix_test.matrix[1][1]);
  ck_assert_double_eq(my_result.matrix[1][2], my_matrix_test.matrix[1][2]);
  ck_assert_double_eq(my_result.matrix[2][0], my_matrix_test.matrix[2][0]);
  ck_assert_double_eq(my_result.matrix[2][1], my_matrix_test.matrix[2][1]);
  ck_assert_double_eq(my_result.matrix[2][2], my_matrix_test.matrix[2][2]);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_inverse_matrix_1) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(3, 3, &my_matrix);
  my_matrix.matrix[0][0] = 0;
  my_matrix.matrix[0][1] = 0;
  my_matrix.matrix[0][2] = 0;
  my_matrix.matrix[1][0] = 2;
  my_matrix.matrix[1][1] = 1;
  my_matrix.matrix[1][2] = 2;
  my_matrix.matrix[2][0] = 4;
  my_matrix.matrix[2][1] = 3;
  my_matrix.matrix[2][2] = 6;
  int error_code = s21_inverse_matrix(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_inverse_matrix_2) {
  matrix_t my_result = {0};
  int error_code = s21_inverse_matrix(NULL, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_inverse_matrix_3) {
  matrix_t my_matrix = {0};
  s21_create_matrix(3, 3, &my_matrix);
  my_matrix.matrix[0][0] = 4;
  my_matrix.matrix[0][1] = 2;
  my_matrix.matrix[0][2] = 2;
  my_matrix.matrix[1][0] = 2;
  my_matrix.matrix[1][1] = 1;
  my_matrix.matrix[1][2] = 2;
  my_matrix.matrix[2][0] = 4;
  my_matrix.matrix[2][1] = 3;
  my_matrix.matrix[2][2] = 6;
  int error_code = s21_inverse_matrix(&my_matrix, NULL);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_inverse_matrix_4) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  s21_create_matrix(4, 3, &my_matrix);
  int error_code = s21_inverse_matrix(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 2);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_inverse_matrix_5) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  my_matrix.rows = -3;
  my_matrix.columns = 3;
  int error_code = s21_inverse_matrix(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_inverse_matrix_6) {
  matrix_t my_matrix = {0};
  matrix_t my_result = {0};
  my_matrix.rows = 3;
  my_matrix.columns = -3;
  int error_code = s21_inverse_matrix(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

START_TEST(Incorrect_input_parameters_s21_inverse_matrix_7) {
  matrix_t my_matrix;
  matrix_t my_result;
  my_matrix.rows = 3;
  my_matrix.columns = 3;
  my_matrix.matrix = NULL;
  int error_code = s21_inverse_matrix(&my_matrix, &my_result);
  ck_assert_int_eq(error_code, 1);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_3);
  tcase_add_test(tc1_1, Incorrect_input_parameters_4);
  tcase_add_test(tc1_1, Incorrect_input_parameters_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_6);
  tcase_add_test(tc1_1, Incorrect_input_parameters_7);
  tcase_add_test(tc1_1, Incorrect_input_parameters_9);
  tcase_add_test(tc1_1, Correct_input_parameters_10);
  tcase_add_test(tc1_1, Correct_input_parameters_11);
  tcase_add_test(tc1_1, Correct_input_parameters_12);
  tcase_add_test(tc1_1, Correct_input_parameters_13);
  tcase_add_test(tc1_1, Correct_input_parameters_14);
  tcase_add_test(tc1_1, Correct_input_parameters_15);
  tcase_add_test(tc1_1, Correct_input_parameters_remove_matrix_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_remove_matrix_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_remove_matrix_2);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_eq_matrix_1);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_eq_matrix_2);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_eq_matrix_3);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_eq_matrix_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_eq_matrix_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_eq_matrix_3);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_eq_matrix_4);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_eq_matrix_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_eq_matrix_6);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_eq_matrix_7);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_eq_matrix_8);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sum_matrix_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sum_matrix_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sum_matrix_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sum_matrix_6);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sum_matrix_7);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sum_matrix_8);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sum_matrix_9);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sum_matrix_10);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sum_matrix_11);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sum_matrix_12);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sum_matrix_13);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sum_matrix_14);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sum_matrix_15);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sum_matrix_16);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sub_matrix_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sub_matrix_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sub_matrix_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sub_matrix_6);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sub_matrix_7);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_sub_matrix_8);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sub_matrix_9);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sub_matrix_10);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sub_matrix_11);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sub_matrix_12);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sub_matrix_13);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sub_matrix_14);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sub_matrix_15);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_sub_matrix_16);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_number_1);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_number_2);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_number_3);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_number_4);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_number_5);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_number_6);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_number_7);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_number_8);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_number_9);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_number_10);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_number_11);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_number_12);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_matrix_1);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_matrix_2);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_matrix_3);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_mult_matrix_4);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_3);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_4);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_6);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_7);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_8);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_9);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_10);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_mult_matrix_11);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_transpose_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_transpose_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_transpose_3);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_transpose_4);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_transpose_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_transpose_6);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_determinant_1);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_determinant_2);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_determinant_3);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_determinant_4);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_determinant_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_determinant_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_determinant_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_determinant_3);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_determinant_4);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_determinant_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_determinant_6);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_determinant_7);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_calc_complements_1);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_calc_complements_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_calc_complements_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_calc_complements_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_calc_complements_3);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_calc_complements_4);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_calc_complements_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_calc_complements_6);
  tcase_add_test(tc1_1, Correct_input_parameters_s21_inverse_matrix_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_inverse_matrix_1);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_inverse_matrix_2);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_inverse_matrix_3);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_inverse_matrix_4);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_inverse_matrix_5);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_inverse_matrix_6);
  tcase_add_test(tc1_1, Incorrect_input_parameters_s21_inverse_matrix_7);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
